### ISSUE TITLE
XePatcher v2.9/3.0 do not work

### ISSUE THREAD

**Issue by jao12345** [grimdoomer/Halo-2-HD#3]
XePatcher v3.0 by Grimdoomer

Compiling Patches... Success

and no output file.

**Comment by grimdoomer** [comment]
Your command line arguments are incorrect, please post the full command line arguments you're using.

**Comment by jao12345** [comment]
XePatcher.exe -p ".\src\halo2_hd_patches.asm" -proc x86 -bin defaultExp.xbe -o newfile.xbe
or
XePatcher.exe -p ".\src\halo2_hd_patches.asm" -proc x86 -bin defaultExp.xbe

**Comment by grimdoomer** [comment]
If you don't provide a full file path the xbe file will need to be in your current working directory. You should use the full file path to the xbe file instead.

The game will not run at 60 fps even with the frame limit removed and will cause issues with physics updates. You'd also have to disable vsync which will result in screen tearing.

**Comment by jao12345** [comment]
Full file path did not help.

**Comment by grimdoomer** [comment]
Try using the full file path for the patch file as well.

**Comment by jao12345** [comment]
I did, full file path 2 times.

**Comment by grimdoomer** [comment]
Can you post a picture of your command prompt window with the full command you're using and XePatcher output?

**Comment by jao12345** [comment]
![pic](https://github.com/user-attachments/assets/f9e7d075-cbf3-4a62-9662-5e374f58a439)

**Comment by grimdoomer** [comment]
Use a full file path for the patch file, ex: "E:\xbox\!Patches\!HALO2\src\halo2_hd_patches.asm"

**Comment by jao12345** [comment]
It's OK now.

**Comment by grimdoomer** [comment]
Updated documentation for this issue.
